### ISSUE TITLE
.cabal-sandbox/bin/kontiki-udp node3

### ISSUE THREAD

**Issue by afcowie** [NicolasT/kontiki#16]
Running

```
$ .cabal-sandbox/bin/kontiki-udp node3
```

Gives

```
kontiki-udp: Map.!: given key is not an element in the map
```

after node0, node1, node2 are up.

**Comment by NicolasT** [comment]
The `kontiki-udp` demo is, really, a very simple stupid demo, which only supports 3 nodes: https://github.com/NicolasT/kontiki/blob/e753c5afd0ff2a00fb674890908484137bec4240/bin/udp.hs#L58

I'm not sure adding support for more is worth the trouble...
