### ISSUE TITLE
Kontiki demos don't run

### ISSUE THREAD

**Issue by ketzacoatl** [NicolasT/kontiki#22]
Hi, I am looking at the various raft implementations in Haskell and came to reviewing the Kontiki demos.

I built the code from `master` with `stack build` and then ran the `kontiki-udp` demo, though it fails:

```
ᐅ kontiki-udp NodeA            
kontiki-udp: Map.!: given key is not an element in the map
```

I believe that is referring to https://github.com/NicolasT/kontiki/blob/master/src/Network/Kontiki/Raft/Leader.hs#L146.

Also, `kontiki-demo` doesn't seem available either:

```
ᐅ kontiki-demo
(WrapState (Follower (FollowerState {_fCurrentTerm = Term 0, _fCommitIndex = Index {unIndex = 0}, _fVotedFor = Nothing})),[CLog "Ignoring heartbeat timeout in Follower state"])
```

Or am I not executing the demo properly?

**Comment by NicolasT** [comment]
It's not `nodeA`, but `node0`, `node1` and `node2`: https://github.com/NicolasT/kontiki/blob/master/bin/udp.hs#L58

**Comment by ketzacoatl** [comment]
Ah, ok.. I hadn't thought about that being hardcoded, but it makes sense. I now see https://github.com/NicolasT/kontiki/blob/c7093d933419ca035313febbe5efd6cc6a6bd76c/bin/demo.hs#L39 and https://github.com/NicolasT/kontiki/blob/c7093d933419ca035313febbe5efd6cc6a6bd76c/README.md#L39 too. Thanks for clarifying!
